services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 921128
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    volumes:
      - my_dbdata:/var/lib/postgres
volumes:
  my_dbdata:
